---
version: "3.7"
services:
  mariadb:
    image: "mariadb"
    container_name: "mariadb"
    hostname: "mariadb"
    restart: unless-stopped
    env_file:
      - ".env"
    volumes:
      - backup:/backups/
      - mariadb_vol:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    labels:
      - "docker-volume-backup.archive-pre=/bin/sh -c 'mysqldump -u ${MYSQL_USER} --password='${MYSQL_PASSWORD}' --all-databases > /backups/vaultwarden_mariadb.sql'"
      - "docker-volume-backup.stop-during-backup=stopservice"
    networks:
      - traefik
  vaultwarden:
    image: vaultwarden/server
    container_name: vaultwarden
    hostname: vaultwarden
    env_file:
      - ".env"
    ports:
      - 7000:80
      - 3012:3012
    environment:
      - WEBSOCKET_ENABLED=true
      # - SIGNUPS_ALLOWED=false
      - DATABASE_URL=${DATABASE_URL}
      - RUST_BACKTRACE=1
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - DOMAIN=https://warden.ypstudio.ru/
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURITY=force_tls
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - LOG_FILE=/data/vaultwarden.log
    volumes:
      - vaultwarden:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`warden.ypstudio.ru`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      - "traefik.http.routers.vaultwarden.tls.certresolver=myresolver"
      - "docker-volume-backup.stop-during-backup=stopservice"
    networks:
      - traefik
volumes:
  vaultwarden:
  mariadb_vol:
  backup:
    name: backup
    external: true
networks:
  traefik:
    name: traefik